// 观赛日历数据 · 2026 世界杯小组赛(72场) + 6、7月 F1(含排位赛/冲刺赛)
// 时间统一存 UTC，程序里换算成 Europe/Amsterdam 显示。世界杯=NOS，F1=F1 TV。
// F1 分段时间据 Sky 官方赛程换算；仅英国站(银石)为冲刺周末。
const allFixtures = [
  {"id": "wc-01", "sport": "worldcup", "title": "A组 · 墨西哥 vs 南非", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-11T19:00:00Z", "venue": "墨西哥城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-02", "sport": "worldcup", "title": "A组 · 韩国 vs 捷克", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-12T02:00:00Z", "venue": "瓜达拉哈拉", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-03", "sport": "worldcup", "title": "B组 · 加拿大 vs 波黑", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-12T19:00:00Z", "venue": "多伦多", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-04", "sport": "worldcup", "title": "D组 · 美国 vs 巴拉圭", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-13T01:00:00Z", "venue": "洛杉矶", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-05", "sport": "worldcup", "title": "B组 · 卡塔尔 vs 瑞士", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-13T19:00:00Z", "venue": "旧金山湾区", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-06", "sport": "worldcup", "title": "C组 · 巴西 vs 摩洛哥", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-13T22:00:00Z", "venue": "纽约/新泽西", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-07", "sport": "worldcup", "title": "C组 · 海地 vs 苏格兰", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-14T01:00:00Z", "venue": "波士顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-08", "sport": "worldcup", "title": "D组 · 澳大利亚 vs 土耳其", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-14T04:00:00Z", "venue": "温哥华", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-09", "sport": "worldcup", "title": "E组 · 德国 vs 库拉索", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-14T17:00:00Z", "venue": "休斯顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-10", "sport": "worldcup", "title": "F组 · 荷兰 vs 日本", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-14T20:00:00Z", "venue": "达拉斯", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-11", "sport": "worldcup", "title": "E组 · 科特迪瓦 vs 厄瓜多尔", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-14T23:00:00Z", "venue": "费城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-12", "sport": "worldcup", "title": "F组 · 瑞典 vs 突尼斯", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-15T02:00:00Z", "venue": "蒙特雷", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-13", "sport": "worldcup", "title": "H组 · 西班牙 vs 佛得角", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-15T16:00:00Z", "venue": "亚特兰大", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-14", "sport": "worldcup", "title": "G组 · 比利时 vs 埃及", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-15T19:00:00Z", "venue": "西雅图", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-15", "sport": "worldcup", "title": "H组 · 沙特 vs 乌拉圭", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-15T22:00:00Z", "venue": "迈阿密", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-16", "sport": "worldcup", "title": "G组 · 伊朗 vs 新西兰", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-16T01:00:00Z", "venue": "洛杉矶", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-17", "sport": "worldcup", "title": "I组 · 法国 vs 塞内加尔", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-16T19:00:00Z", "venue": "纽约/新泽西", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-18", "sport": "worldcup", "title": "I组 · 伊拉克 vs 挪威", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-16T22:00:00Z", "venue": "波士顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-19", "sport": "worldcup", "title": "J组 · 阿根廷 vs 阿尔及利亚", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-17T01:00:00Z", "venue": "堪萨斯城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-20", "sport": "worldcup", "title": "J组 · 奥地利 vs 约旦", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-17T04:00:00Z", "venue": "旧金山湾区", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-21", "sport": "worldcup", "title": "K组 · 葡萄牙 vs 刚果(金)", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-17T17:00:00Z", "venue": "休斯顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-22", "sport": "worldcup", "title": "L组 · 英格兰 vs 克罗地亚", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-17T20:00:00Z", "venue": "达拉斯", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-23", "sport": "worldcup", "title": "L组 · 加纳 vs 巴拿马", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-17T23:00:00Z", "venue": "多伦多", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-24", "sport": "worldcup", "title": "K组 · 乌兹别克斯坦 vs 哥伦比亚", "stage": "小组赛第1轮", "datetimeUTC": "2026-06-18T02:00:00Z", "venue": "墨西哥城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-25", "sport": "worldcup", "title": "A组 · 捷克 vs 南非", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-18T16:00:00Z", "venue": "亚特兰大", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-26", "sport": "worldcup", "title": "B组 · 瑞士 vs 波黑", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-18T19:00:00Z", "venue": "洛杉矶", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-27", "sport": "worldcup", "title": "B组 · 加拿大 vs 卡塔尔", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-18T22:00:00Z", "venue": "温哥华", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-28", "sport": "worldcup", "title": "A组 · 墨西哥 vs 韩国", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-19T01:00:00Z", "venue": "瓜达拉哈拉", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-29", "sport": "worldcup", "title": "D组 · 美国 vs 澳大利亚", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-19T19:00:00Z", "venue": "西雅图", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-30", "sport": "worldcup", "title": "C组 · 苏格兰 vs 摩洛哥", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-19T22:00:00Z", "venue": "波士顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-31", "sport": "worldcup", "title": "C组 · 巴西 vs 海地", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-20T01:00:00Z", "venue": "费城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-32", "sport": "worldcup", "title": "D组 · 土耳其 vs 巴拉圭", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-20T04:00:00Z", "venue": "旧金山湾区", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-33", "sport": "worldcup", "title": "F组 · 荷兰 vs 瑞典", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-20T17:00:00Z", "venue": "休斯顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-34", "sport": "worldcup", "title": "E组 · 德国 vs 科特迪瓦", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-20T20:00:00Z", "venue": "多伦多", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-35", "sport": "worldcup", "title": "E组 · 厄瓜多尔 vs 库拉索", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-21T00:00:00Z", "venue": "堪萨斯城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-36", "sport": "worldcup", "title": "F组 · 突尼斯 vs 日本", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-21T04:00:00Z", "venue": "蒙特雷", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-37", "sport": "worldcup", "title": "H组 · 西班牙 vs 沙特", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-21T16:00:00Z", "venue": "亚特兰大", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-38", "sport": "worldcup", "title": "G组 · 比利时 vs 伊朗", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-21T19:00:00Z", "venue": "洛杉矶", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-39", "sport": "worldcup", "title": "H组 · 乌拉圭 vs 佛得角", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-21T22:00:00Z", "venue": "迈阿密", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-40", "sport": "worldcup", "title": "G组 · 新西兰 vs 埃及", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-22T01:00:00Z", "venue": "温哥华", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-41", "sport": "worldcup", "title": "J组 · 阿根廷 vs 奥地利", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-22T17:00:00Z", "venue": "达拉斯", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-42", "sport": "worldcup", "title": "I组 · 法国 vs 伊拉克", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-22T21:00:00Z", "venue": "费城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-43", "sport": "worldcup", "title": "I组 · 挪威 vs 塞内加尔", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-23T00:00:00Z", "venue": "纽约/新泽西", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-44", "sport": "worldcup", "title": "J组 · 约旦 vs 阿尔及利亚", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-23T03:00:00Z", "venue": "旧金山湾区", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-45", "sport": "worldcup", "title": "K组 · 葡萄牙 vs 乌兹别克斯坦", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-23T17:00:00Z", "venue": "休斯顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-46", "sport": "worldcup", "title": "L组 · 英格兰 vs 加纳", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-23T20:00:00Z", "venue": "波士顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-47", "sport": "worldcup", "title": "L组 · 巴拿马 vs 克罗地亚", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-23T23:00:00Z", "venue": "多伦多", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-48", "sport": "worldcup", "title": "K组 · 哥伦比亚 vs 刚果(金)", "stage": "小组赛第2轮", "datetimeUTC": "2026-06-24T02:00:00Z", "venue": "瓜达拉哈拉", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-49", "sport": "worldcup", "title": "B组 · 瑞士 vs 加拿大", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-24T19:00:00Z", "venue": "温哥华", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-50", "sport": "worldcup", "title": "B组 · 波黑 vs 卡塔尔", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-24T19:00:00Z", "venue": "西雅图", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-51", "sport": "worldcup", "title": "C组 · 苏格兰 vs 巴西", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-24T22:00:00Z", "venue": "迈阿密", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-52", "sport": "worldcup", "title": "C组 · 摩洛哥 vs 海地", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-24T22:00:00Z", "venue": "亚特兰大", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-53", "sport": "worldcup", "title": "A组 · 捷克 vs 墨西哥", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-25T01:00:00Z", "venue": "墨西哥城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-54", "sport": "worldcup", "title": "A组 · 南非 vs 韩国", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-25T01:00:00Z", "venue": "蒙特雷", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-55", "sport": "worldcup", "title": "E组 · 库拉索 vs 科特迪瓦", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-25T20:00:00Z", "venue": "费城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-56", "sport": "worldcup", "title": "E组 · 厄瓜多尔 vs 德国", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-25T20:00:00Z", "venue": "纽约/新泽西", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-57", "sport": "worldcup", "title": "F组 · 日本 vs 瑞典", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-25T23:00:00Z", "venue": "达拉斯", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-58", "sport": "worldcup", "title": "F组 · 突尼斯 vs 荷兰", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-25T23:00:00Z", "venue": "堪萨斯城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-59", "sport": "worldcup", "title": "D组 · 土耳其 vs 美国", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-26T02:00:00Z", "venue": "洛杉矶", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-60", "sport": "worldcup", "title": "D组 · 巴拉圭 vs 澳大利亚", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-26T02:00:00Z", "venue": "旧金山湾区", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-61", "sport": "worldcup", "title": "I组 · 挪威 vs 法国", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-26T19:00:00Z", "venue": "波士顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-62", "sport": "worldcup", "title": "I组 · 塞内加尔 vs 伊拉克", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-26T19:00:00Z", "venue": "多伦多", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-63", "sport": "worldcup", "title": "H组 · 佛得角 vs 沙特", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-27T00:00:00Z", "venue": "休斯顿", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-64", "sport": "worldcup", "title": "H组 · 乌拉圭 vs 西班牙", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-27T00:00:00Z", "venue": "瓜达拉哈拉", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-65", "sport": "worldcup", "title": "G组 · 埃及 vs 伊朗", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-27T03:00:00Z", "venue": "西雅图", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-66", "sport": "worldcup", "title": "G组 · 新西兰 vs 比利时", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-27T03:00:00Z", "venue": "温哥华", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-67", "sport": "worldcup", "title": "L组 · 巴拿马 vs 英格兰", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-27T21:00:00Z", "venue": "纽约/新泽西", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-68", "sport": "worldcup", "title": "L组 · 克罗地亚 vs 加纳", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-27T21:00:00Z", "venue": "费城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-69", "sport": "worldcup", "title": "K组 · 哥伦比亚 vs 葡萄牙", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-27T23:30:00Z", "venue": "迈阿密", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-70", "sport": "worldcup", "title": "K组 · 刚果(金) vs 乌兹别克斯坦", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-27T23:30:00Z", "venue": "亚特兰大", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-71", "sport": "worldcup", "title": "J组 · 阿尔及利亚 vs 奥地利", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-28T02:00:00Z", "venue": "堪萨斯城", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "wc-72", "sport": "worldcup", "title": "J组 · 约旦 vs 阿根廷", "stage": "小组赛第3轮", "datetimeUTC": "2026-06-28T02:00:00Z", "venue": "达拉斯", "platform": "NOS", "streamUrl": "https://nos.nl/live"},
  {"id": "f1-01", "sport": "f1", "title": "F1 摩纳哥大奖赛 · 排位赛", "stage": "排位赛", "datetimeUTC": "2026-06-06T14:00:00Z", "venue": "摩纳哥 / 蒙特卡洛", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-02", "sport": "f1", "title": "F1 摩纳哥大奖赛 · 正赛", "stage": "正赛", "datetimeUTC": "2026-06-07T13:00:00Z", "venue": "摩纳哥 / 蒙特卡洛", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-03", "sport": "f1", "title": "F1 西班牙大奖赛 · 排位赛", "stage": "排位赛", "datetimeUTC": "2026-06-13T14:00:00Z", "venue": "西班牙 / 巴塞罗那", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-04", "sport": "f1", "title": "F1 西班牙大奖赛 · 正赛", "stage": "正赛", "datetimeUTC": "2026-06-14T13:00:00Z", "venue": "西班牙 / 巴塞罗那", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-05", "sport": "f1", "title": "F1 奥地利大奖赛 · 排位赛", "stage": "排位赛", "datetimeUTC": "2026-06-27T14:00:00Z", "venue": "奥地利 / 施皮尔贝格", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-06", "sport": "f1", "title": "F1 奥地利大奖赛 · 正赛", "stage": "正赛", "datetimeUTC": "2026-06-28T13:00:00Z", "venue": "奥地利 / 施皮尔贝格", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-07", "sport": "f1", "title": "F1 英国大奖赛 · 冲刺排位赛", "stage": "冲刺排位赛", "datetimeUTC": "2026-07-03T15:30:00Z", "venue": "英国 / 银石", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-08", "sport": "f1", "title": "F1 英国大奖赛 · 冲刺赛", "stage": "冲刺赛", "datetimeUTC": "2026-07-04T11:00:00Z", "venue": "英国 / 银石", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-09", "sport": "f1", "title": "F1 英国大奖赛 · 排位赛", "stage": "排位赛", "datetimeUTC": "2026-07-04T15:00:00Z", "venue": "英国 / 银石", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-10", "sport": "f1", "title": "F1 英国大奖赛 · 正赛", "stage": "正赛", "datetimeUTC": "2026-07-05T14:00:00Z", "venue": "英国 / 银石", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-11", "sport": "f1", "title": "F1 比利时大奖赛 · 排位赛", "stage": "排位赛", "datetimeUTC": "2026-07-18T14:00:00Z", "venue": "比利时 / 斯帕", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-12", "sport": "f1", "title": "F1 比利时大奖赛 · 正赛", "stage": "正赛", "datetimeUTC": "2026-07-19T13:00:00Z", "venue": "比利时 / 斯帕", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-13", "sport": "f1", "title": "F1 匈牙利大奖赛 · 排位赛", "stage": "排位赛", "datetimeUTC": "2026-07-25T14:00:00Z", "venue": "匈牙利 / 布达佩斯", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"},
  {"id": "f1-14", "sport": "f1", "title": "F1 匈牙利大奖赛 · 正赛", "stage": "正赛", "datetimeUTC": "2026-07-26T13:00:00Z", "venue": "匈牙利 / 布达佩斯", "platform": "F1 TV", "streamUrl": "https://f1tv.formula1.com"}
];

if (typeof module !== 'undefined') { module.exports = allFixtures; }
